name: AutoSpigotReload
version: 1.2
description: Automatically reloads the server when specific files are updated
api-version: 1.8
main: fr.caemur.autospigotreload.AutoSpigotReload

commands:
  autospigotreload:
    permission: autospigotreload.admin
    aliases: asr

permissions:
  autospigotreload.admin:
    default: op
